### PR TITLE
Added _wire->begin() to Adafruit_MCP9808::begin()

### PR DESCRIPTION
**Pull request by matsen75**
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

_Added _wire->begin() to Adafruit_MCP9808::begin()._ 

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

_None that I know of._

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

_Only difference is that Adafruit_MCP9808::begin() returns true. It was possible to read sensor values even though Adafruit_MCP9808::begin() returned false._

### CODE REVIEW

**Comment by ladyada** [comment]
ahh maybe we should put it in init()? then we'll get all the versions covered!

**Comment by matsen75** [comment]
Not sure,

Is it safe to call _wire.begin() more than once without side effects?

Adafruit_MCP9808::begin(...) takes a TwoWire argument. Someone might have called wire.begin() before passing it to Adafruit_MCP9808.

**Comment by ladyada** [comment]
you can begin() wire many times

**Comment by matsen75** [comment]
Fixed, moved _wire->begin() to init()

**Pull request merged**
